/*
 * JS for catalogo_detalle_blue generated by Exadel Tiggzi
 *
 * Created on: Wednesday, November 21, 2012, 07:28:49 PM (PST)
 */
/************************************
 * JS API provided by Exadel Tiggzi  *
 ************************************/
/* Setting project environment indicator */
Tiggr.env = "bundle";
Tiggr.getProjectGUID = function() {
    return '590393b3-68b2-4942-8d51-7378c56bbc43';
}
Tiggr.getTargetPlatform = function() {
    return '0';
}

function navigateTo(outcome, useAjax) {
    Tiggr.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Tiggr.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Tiggr.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Tiggr.setDetailContent(pageUrl);
}
/**********************
 * SECURITY CONTEXTS  *
 **********************/
/*******************************
 *      SERVICE SETTINGS        *
 ********************************/
/*************************
 *      SERVICES          *
 *************************/
createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
Tiggr.AppPages = [{
    "name": "catalogo_detalle_nefesh",
    "location": "catalogo_detalle_nefesh.html"
}, {
    "name": "catalogo_detalle_fondo",
    "location": "catalogo_detalle_fondo.html"
}, {
    "name": "Menu",
    "location": "Menu.html"
}, {
    "name": "catalogo_detalle_blue",
    "location": "catalogo_detalle_blue.html"
}, {
    "name": "distribuidoreszona",
    "location": "distribuidoreszona.html"
}, {
    "name": "verpedido",
    "location": "verpedido.html"
}, {
    "name": "Inicio",
    "location": "Inicio.html"
}, {
    "name": "catalogo",
    "location": "catalogo.html"
}, {
    "name": "map_distribuidores",
    "location": "map_distribuidores.html"
}, {
    "name": "status_pedido",
    "location": "status_pedido.html"
}, {
    "name": "pedido",
    "location": "pedido.html"
}];
j_42_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobileimage_2': 'j_43',
        'mobilelabel1_3': 'j_44',
        'mobilelabel1_4': 'j_45',
        'mobilecheckboxgroup1_5': 'j_46',
        'mobilecheckbox1_8': 'j_47',
        'mobilelabel1_9': 'j_48'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    Tiggr.CurrentScreen = 'j_42';
    /*************************
     * NONVISUAL COMPONENTS  *
     *************************/
    var datasources = [];
    /************************
     * EVENTS AND HANDLERS  *
     ************************/
    j_42_beforeshow = function() {
        Tiggr.CurrentScreen = 'j_42';
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }
    // screen onload
    screen_F0E1_onLoad = j_42_onLoad = function() {
        screen_F0E1_elementsExtraJS();
        j_42_windowEvents();
        screen_F0E1_elementsEvents();
    }
    // screen window events
    screen_F0E1_windowEvents = j_42_windowEvents = function() {
        $('#j_42').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });
    }
    // screen elements extra js
    screen_F0E1_elementsExtraJS = j_42_elementsExtraJS = function() {
        // screen (screen-F0E1) extra code
    }
    // screen elements handler
    screen_F0E1_elementsEvents = j_42_elementsEvents = function() {
        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });
    }
    $("#j_42").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        j_42_beforeshow();
    });
    if (runBeforeShow) {
        j_42_beforeshow();
    } else {
        j_42_onLoad();
    }
}
$("#j_42").die("pageinit").live("pageinit", function(event, ui) {
    j_42_js();
});