/*
 * JS for catalogo generated by Exadel Tiggzi
 *
 * Created on: Wednesday, November 21, 2012, 07:28:49 PM (PST)
 */
/************************************
 * JS API provided by Exadel Tiggzi  *
 ************************************/
/* Setting project environment indicator */
Tiggr.env = "bundle";
Tiggr.getProjectGUID = function() {
    return '590393b3-68b2-4942-8d51-7378c56bbc43';
}
Tiggr.getTargetPlatform = function() {
    return '0';
}

function navigateTo(outcome, useAjax) {
    Tiggr.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Tiggr.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Tiggr.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Tiggr.setDetailContent(pageUrl);
}
/**********************
 * SECURITY CONTEXTS  *
 **********************/
/*******************************
 *      SERVICE SETTINGS        *
 ********************************/
/*************************
 *      SERVICES          *
 *************************/
createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
Tiggr.AppPages = [{
    "name": "catalogo_detalle_nefesh",
    "location": "catalogo_detalle_nefesh.html"
}, {
    "name": "catalogo_detalle_fondo",
    "location": "catalogo_detalle_fondo.html"
}, {
    "name": "Menu",
    "location": "Menu.html"
}, {
    "name": "catalogo_detalle_blue",
    "location": "catalogo_detalle_blue.html"
}, {
    "name": "distribuidoreszona",
    "location": "distribuidoreszona.html"
}, {
    "name": "verpedido",
    "location": "verpedido.html"
}, {
    "name": "Inicio",
    "location": "Inicio.html"
}, {
    "name": "catalogo",
    "location": "catalogo.html"
}, {
    "name": "map_distribuidores",
    "location": "map_distribuidores.html"
}, {
    "name": "status_pedido",
    "location": "status_pedido.html"
}, {
    "name": "pedido",
    "location": "pedido.html"
}];
j_113_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilecollapsblock1_2': 'j_114',
        'mobilecollapsblockheader1_3': 'j_115',
        'mobileimage_9': 'j_116',
        'mobilecollapsblockcontent1_4': 'j_117',
        'mobilelist1_5': 'j_118',
        'nefesh1': 'j_119',
        'mobilelistitem1_8': 'j_120',
        'mobilelistitem1_49': 'j_121',
        'mobilelistitem1_50': 'j_122',
        'mobilelistitem1_51': 'j_123',
        'mobilecollapsblock1_41': 'j_124',
        'mobilecollapsblockheader1_42': 'j_125',
        'mobileimage_47': 'j_126',
        'mobilecollapsblockcontent1_43': 'j_127',
        'mobilelist1_52': 'j_128',
        'opcion_fondo': 'j_129',
        'mobilelistitem1_54': 'j_130',
        'mobilelistitem1_55': 'j_131',
        'mobilelistitem1_56': 'j_132',
        'mobilelistitem1_57': 'j_133',
        'mobilecollapsblock1_62': 'j_134',
        'mobilecollapsblockheader1_63': 'j_135',
        'mobileimage_65': 'j_136',
        'mobilecollapsblockcontent1_64': 'j_137',
        'mobilelist1_66': 'j_138',
        'opcion3_blue': 'j_139',
        'mobilelistitem1_68': 'j_140',
        'mobilelistitem1_69': 'j_141',
        'mobilelistitem1_70': 'j_142',
        'mobilelistitem1_71': 'j_143'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    Tiggr.CurrentScreen = 'j_113';
    /*************************
     * NONVISUAL COMPONENTS  *
     *************************/
    var datasources = [];
    /************************
     * EVENTS AND HANDLERS  *
     ************************/
    j_113_beforeshow = function() {
        Tiggr.CurrentScreen = 'j_113';
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }
    // screen onload
    screen_3A6F_onLoad = j_113_onLoad = function() {
        screen_3A6F_elementsExtraJS();
        j_113_windowEvents();
        screen_3A6F_elementsEvents();
    }
    // screen window events
    screen_3A6F_windowEvents = j_113_windowEvents = function() {
        $('#j_113').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });
        $('#j_113').bind({
            unload: function() {
                Tiggr.navigateTo('Menu', {
                    reverse: false
                });
            },
        });
    }
    // screen elements extra js
    screen_3A6F_elementsExtraJS = j_113_elementsExtraJS = function() {
        // screen (screen-3A6F) extra code
        listView = $("#j_118");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#j_118 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
        listView = $("#j_128");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#j_128 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
        listView = $("#j_138");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#j_138 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
    }
    // screen elements handler
    screen_3A6F_elementsEvents = j_113_elementsEvents = function() {
        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });
        $('#j_3 [name="nefesh1"]').die().live({
            tap: function() {
                Tiggr.navigateTo('catalogo_detalle_nefesh', {
                    reverse: false
                });
            },
        });
        $('#j_3 [name="opcion_fondo"]').die().live({
            tap: function() {
                Tiggr.navigateTo('catalogo_detalle_fondo', {
                    reverse: false
                });
            },
        });
        $('#j_3 [name="opcion3_blue"]').die().live({
            tap: function() {
                Tiggr.navigateTo('catalogo_detalle_blue', {
                    reverse: false
                });
            },
        });
    }
    $("#j_113").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        j_113_beforeshow();
    });
    if (runBeforeShow) {
        j_113_beforeshow();
    } else {
        j_113_onLoad();
    }
}
$("#j_113").die("pageinit").live("pageinit", function(event, ui) {
    j_113_js();
});